version: '3.8'

services:
  blogvue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogvue
    ports:
      - "80:80"
    environment:
      # 修改此处配置 API 地址
      - API_BASE_URL=http://your-api-server:6101/blog
    restart: unless-stopped
